# Generated by Django 5.1.1 on 2024-09-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provincelist',
            old_name='Province',
            new_name='Provinces',
        ),
    ]
