# Generated by Django 5.1.1 on 2024-09-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_rename_province_provincelist_provinces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincelist',
            name='remark',
        ),
    ]
